version: '3'

services:
  redis:
    image: redis:6
    ports:
      - '6379:6379'
  
  web: 
    build:
      context: therapist
    command: daphne -b 0.0.0.0 -p 8000 therapist.asgi:application
    volumes:
      - ./therapist:/app
    ports: 
      - '8000:8000'